### ISSUE TITLE
Add an HTTP or HTTPS option for docker push

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/plugin-docker#32]
### Feature description

Given the following code : 

```yaml
  - id: build_powershell_image
    type: io.kestra.plugin.docker.Build
    credentials:
      password: <password>
      registry: http://10.100.130.35:9001/repository/docker-hosted
      username: <username>
    dockerfile: "FROM mcr.microsoft.com/powershell:latest\r

      RUN pwsh -c \"Install-Module Microsoft.Graph -Scope CurrentUser -AllowClobber -Force\""
    platforms:
      - linux/amd64
    push: true
    tags:
      - 10.100.130.35:9001/admin-powershell:latest
 ```

despite setting the registry URL to http:// the task tries to push using https. My private registry is using an HTTP listener. 
Please add an HTTP or HTTPS option so that we have the ability to choose.

![image](https://github.com/user-attachments/assets/4730f072-3704-46dd-a56c-7ba474bab1ad)
