### ISSUE TITLE
Docker push not working because RepositoryName contains scheme

### ISSUE THREAD

**Issue by larsgerber** [kestra-io/plugin-docker#37]
### Expected Behavior

Hello everyone

I updated from Kestra `v0.18.9` to `v0.19.1` today. It seems like Docker push is not working anymore.

The following error is displayed:

![Screenshot 2024-10-06 at 19 10 43](https://github.com/user-attachments/assets/5a118363-02ee-454a-8900-b6a1772bf1f6)

Source off error message: https://github.com/docker-java/docker-java/blob/a1393bf2e1265ba1e6eca4240af55396852f8a7c/docker-java-core/src/main/java/com/github/dockerjava/core/NameParser.java#L104

I think the issue is caused by the following change:
https://github.com/kestra-io/plugin-docker/commit/b759e7b2aa9f9e1e86da5a8fcb2e0b3c5758d6e9

### Actual Behaviour

Docker push works like in version `v0.18.9`.

### Steps To Reproduce

1. copy example from below
2. paste into flow
3. run
4. check logs

### Environment Information

- Kestra Version: v0.19.1
- Plugin version: v0.19.0
- Operating System (OS / Docker / Kubernetes): Docker version 26.1.3
- Java Version (If not docker):

### Example flow

```yaml
- id: publish
  type: io.kestra.plugin.docker.Build
  platforms:
    - linux/amd64
  credentials:
    registry: "docker.example.com"
    auth: "{{ secret('DOCKER_REGISTRY') }}"
  dockerfile: Dockerfile
  push: true
  tags:
    - "docker.example.com/acme:1.0.3"
    - "docker.example.com/acme:latest"
  disabled: false
```
