### ISSUE TITLE
Dockerfiles with TARGETARCH and TARGETOS do not respect `platforms` values

### ISSUE THREAD

**Issue by danlsgiga** [kestra-io/plugin-docker#40]
### Describe the issue

When trying to build a docker image that has the following blocks, the build args are not being auto generated.

```
ARG TARGETOS
ARG TARGETARCH
```

Once I hardcode those via `buildArgs`, the build works.

```
buildArgs:
   TARGETARCH: amd64
   TARGETOS: linux
```

This is the flow code I'm using:

```
id: docker_build
namespace: github-runner
description: Build github runner Docker image
disabled: false

labels:
  component: github-runner

inputs:
  - id: release
    type: STRING
    defaults: v2.321.0

triggers:
  - id: listen_release_trigger
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      release: "{{ outputs.release.values.latest ?? inputs.release }}"
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: github-runner
        flowId: release_trigger
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
    
tasks:
  - id: build
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: git_pull
        type: io.kestra.plugin.git.Clone
        branch: main
        url: https://github.com/actions/runner.git
      - id: image
        retry: 
          type: constant
          maxAttempt: 5
          interval: PT5M
        type: io.kestra.plugin.docker.Build
        dockerfile: images/Dockerfile
        buildArgs:
          RUNNER_VERSION: "{{ inputs.release | substringAfter('v') }}"
          TARGETARCH: amd64
          TARGETOS: linux
        tags:
          - danlsgiga/github-runner:latest
          - "danlsgiga/github-runner:{{ inputs.release | substringAfter('v') }}"
        platforms:
          - linux/amd64
```

### Environment

- Kestra Version: v0.19.11
