### ISSUE TITLE
Docker run failing with 404 when registry provided

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-docker#50]
### Describe the issue

```
id: docker_run
namespace: demo

tasks:
  - id: run
    type: io.kestra.plugin.docker.Run
    containerImage: docker/kestra-ee:latest-no-plugins
    credentials:
      username: {{secret('username')}}
      password: {{secret('pass')}}
      registry: registry.kestra.io
```

this gives 404. whereas the following succeeds

```
id: docker_run
namespace: demo

tasks:
  - id: run
    type: io.kestra.plugin.docker.Run
    containerImage: registry.kestra.io/docker/kestra-ee:latest-no-plugins
    credentials:
      username: {{secret('username')}}
      password: {{secret('pass')}}
```

### Environment

- Kestra Version: 0.20.12
