### ISSUE TITLE
Add Docker Pull and Docker Prune tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-docker#52]
### Feature description

to manage the container lifecycle on a given worker

**Comment by mgabelle** [comment]
I also was wondering f it was relevant to add to the `Run` task the `containerId` in the outputs.
I don't know how to easily stop the container once runned with the `Stop` task that requires a containerId. 
What do you think ?

**Comment by mgabelle** [comment]
Can you give me more informations about these two new tasks ? 

- Pull : I guess we just want to pull an image (for what use ? Run already pull and run the image) 
- Prune: are you referring to [docker system prune](https://docs.docker.com/reference/cli/docker/system/prune/) command

**Comment by anna-geller** [comment]
for first one: Yup, already output: `{{ outputs.star.taskRunner.containerId }}`


```yaml
id: dockerRedis
namespace: company.team

variables:
  host: host.docker.internal

tasks:
  - id: start
    type: io.kestra.plugin.docker.Run
    containerImage: redis
    wait: false
    portBindings:
      - "6379:6379"

  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT1S
    description: Wait for the Redis container to start

  - id: set
    type: io.kestra.plugin.redis.string.Set
    url: "redis://:redis@{{vars.host}}:6379/0"
    key: "key_string_{{execution.id}}"
    value: "{{flow.id}}"
    serdeType: STRING

  - id: get
    type: io.kestra.plugin.redis.string.Get
    url: "redis://:redis@{{vars.host}}:6379/0"
    key: "key_string_{{execution.id}}"
    serdeType: STRING

  - id: assert
    type: io.kestra.plugin.core.execution.Assert
    errorMessage: "Invalid get data {{outputs.get}}"
    conditions:
      - "{{outputs.get.data == flow.id}}"

  - id: delete
    type: io.kestra.plugin.redis.string.Delete
    url: "redis://:redis@{{vars.host}}:6379/0"
    keys:
      - "key_string_{{execution.id}}"

  - id: getAfterDelete
    type: io.kestra.plugin.redis.string.Get
    url: "redis://:redis@{{vars.host}}:6379/0"
    key: "key_string_{{execution.id}}"
    serdeType: STRING

  - id: assertAfterDelete
    type: io.kestra.plugin.core.execution.Assert
    errorMessage: "Invalid get data {{outputs.getAfterDelete}}"
    conditions:
      - "{{(outputs.getAfterDelete contains 'data') == false}}"

finally:
  - id: stop
    type: io.kestra.plugin.docker.Stop
    containerId: "{{outputs.start.taskRunner.containerId}}"
```

**Comment by anna-geller** [comment]
## Docker Pull

Main use case: when user has large container images and prefers to have separate task to pull them to a given worker e.g. on schedule.

```yaml
id: dockerPull
namespace: system

tasks:
  - id: ee
    type: io.kestra.plugin.docker.Pull
    containerImage: "redis:latest"
    workerGroup:
      key: myworker
```

Matt TBD which extra properties might be useful based on what is available in the Java SDK. Example props we see in CLI:

```yaml
➜  ~ docker pull --help

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Download an image from a registry

Aliases:
  docker image pull, docker pull

Options:
  -a, --all-tags                Download all tagged images in the repository
      --disable-content-trust   Skip image verification (default true)
      --platform string         Set platform if server is multi-platform
                                capable
  -q, --quiet                   Suppress verbose output
```
