### ISSUE TITLE
Add Bearer-token support for Docker Registry v2

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-docker#66]
### Describe the issue

Right now the Docker plugin only does basic auth against `/v1/` registry https://index.docker.io/v1/, which limits us to the old registry endpoint. If you point it at a v2 server https://registry-1.docker.io/v2/, you get a 401 because there’s no token handshake.

It’d be great if the plugin could:
* Detect a `WWW-Authenticate: Bearer` challenge
* Fetch an access token from the registry’s auth service
* Retry the request with `Authorization: Bearer <token>`
* Cache the token until it expires

That way users can push and pull directly against `registry-1.docker.io/v2/` (and other v2-only registries) without falling back to the deprecated v1 API.

## Current workaround 

Atm, user needs to use basic auth against the deprecated v1 Registry API:

```yaml
id: build_dockerhub_image
namespace: company.team

tasks:
  - id: build
    type: io.kestra.plugin.docker.Build
    dockerfile: |
      FROM python:3.12-slim
      RUN pip install kestra
    tags:
      - annageller/kestra:latest
    push: true
    credentials:
      username: annageller
      password: dckr_pat_xxxxxxxx
      registry: https://index.docker.io/v1/ # works
      # registry: https://registry-1.docker.io/v2/ # doesn't work
``` 

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
explore registry token and identity token which are already available as properties -- will need a cleanup anyway

**Comment by KhalefAhmed** [comment]
@loicmathieu I would like your advice on this issue:

I added the [RegistryAuthAwareDockerHttpClient](https://github.com/KhalefAhmed/kestra/blob/ISSUE-2867/script/src/main/java/io/kestra/plugin/scripts/runner/docker/RegistryAuthAwareDockerHttpClient.java) class in the scripts module, which implements DockerHttpClient. The goal is to intercept the 401 error and follow the authentication scheme described in the [Docker Registry v2 authentication specification](https://distribution.github.io/distribution/spec/auth/token/).

However, I'm encountering two problems:

1. The client responds with a 200 status code to indicate that the request has been executed, but the error is transmitted via the ResultCallback.

2. In the plugin, when I try to intercept the error in the ResultCallback and retrieve additional information, I only get the error message without any additional details.

I've opened an [issue](https://github.com/docker-java/docker-java/issues/2442) in the Docker API to request  implemention fir the Registry v2 authentication.

Do you have any suggestions on how to implement this authentication ?

This week, I plan to examine the docker-java code directly to see how I could implement this functionality or at least obtain more information via the ResultCallback.

Thank you in advance for your help!

**Comment by loicmathieu** [comment]
@KhalefAhmed I didn't investiguate this issue so I don't know how to help you. Opening an issue on the client repository seems the right things to do, let's wait for their advise.

**Comment by fdelbrayelle** [comment]
Hi 👋 Since the [issue](https://github.com/docker-java/docker-java/issues/2442) didn't move on docker-java, let's move this on 1.0 release.

**Comment by Pradumnasaraf** [comment]
Working as expected ✅. Sharing code in case of need for docs 

```yaml
id: push_to_dockerhub_v2_registry
namespace: docker_qa
description: |
  Pushes a tiny image to Docker Hub using the v2 registry URL
  (`https://registry-1.docker.io/v2/`). Before kestra#15141, the daemon could
  not find the credentials because Kestra stored them under the v2 URL key
  instead of the canonical Docker Hub key `https://index.docker.io/v1/`.
  A green push here means the URL normalization is in effect.

tasks:
  - id: build_and_push
    type: io.kestra.plugin.docker.Build
    credentials:
      registry: https://registry-1.docker.io/v2/
      username: "{{ secret('DOCKERHUB_USERNAME') }}"
      password: "{{ secret('DOCKERHUB_TOKEN') }}"
    push: true
    tags:
      - pradumnakestra/kestra-qa-docker-registry-v2:latest
    dockerfile: |
      FROM alpine:3.20
      RUN echo "kestra-qa docker registry v2 push test" > /hello.txt
      CMD ["cat", "/hello.txt"]

```

<img width="1278" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f78408ba-210c-49ca-a969-da4d60cd433b" />
